(function(){'use strict';
function f(a){return function(){return a}}var k,l="object"===typeof __ScalaJSEnv&&__ScalaJSEnv?__ScalaJSEnv:{},m="object"===typeof l.global&&l.global?l.global:"object"===typeof global&&global&&global.Object===Object?global:this;l.global=m;var aa="object"===typeof l.exportsNamespace&&l.exportsNamespace?l.exportsNamespace:m;l.exportsNamespace=aa;m.Object.freeze(l);var ba={envInfo:l,semantics:{asInstanceOfs:2,moduleInit:2,strictFloats:!1,productionMode:!0},assumingES6:!1,linkerVersion:"0.6.10"};m.Object.freeze(ba);
m.Object.freeze(ba.semantics);var n=m.Math.imul||function(a,b){var c=a&65535,d=b&65535;return c*d+((a>>>16&65535)*d+c*(b>>>16&65535)<<16>>>0)|0},ca=m.Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&4294901760)&&(a<<=16,b+=16);0===(a&4278190080)&&(a<<=8,b+=8);0===(a&4026531840)&&(a<<=4,b+=4);0===(a&3221225472)&&(a<<=2,b+=2);return b+(a>>31)},da=0,ea=m.WeakMap?new m.WeakMap:null;function r(a){return function(b,c){return!(!b||!b.a||b.a.ma!==c||b.a.ka!==a)}}
function fa(a){for(var b in a)return b}function ga(a,b){return ha(a,b,0)}function ha(a,b,c){var d=new a.eb(b[c]);if(c<b.length-1){a=a.oa;c+=1;for(var e=d.g,g=0;g<e.length;g++)e[g]=ha(a,b,c)}return d}function ia(a){return void 0===a?"undefined":a.toString()}
function ja(a){switch(typeof a){case "string":return s(ka);case "number":var b=a|0;return b===a?b<<24>>24===b&&1/b!==1/-0?s(la):b<<16>>16===b&&1/b!==1/-0?s(ma):s(na):"number"===typeof a?s(oa):s(pa);case "boolean":return s(qa);case "undefined":return s(ra);default:return null===a?a.ae():v(a)?s(sa):a&&a.a?s(a.a):null}}function ta(a,b){return a&&a.a||null===a?a.q(b):"number"===typeof a?"number"===typeof b&&(a===b?0!==a||1/a===1/b:a!==a&&b!==b):a===b}
function ua(a){switch(typeof a){case "string":return va(w(),a);case "number":return wa(xa(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.a||null===a?a.t():null===ea?42:ya(a)}}function za(a){return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}function Aa(a,b){for(var c=m.Object.getPrototypeOf,d=m.Object.getOwnPropertyDescriptor,e=c(a);null!==e;){var g=d(e,b);if(void 0!==g)return g;e=c(e)}}
function Ba(a,b,c){a=Aa(a,c);if(void 0!==a)return c=a.get,void 0!==c?c.call(b):a.value}function Ca(a,b,c,d){a=Aa(a,c);if(void 0!==a&&(a=a.set,void 0!==a)){a.call(b,d);return}throw new m.TypeError("super has no setter '"+c+"'.");}
var ya=null!==ea?function(a){switch(typeof a){case "string":case "number":case "boolean":case "undefined":return ua(a);default:if(null===a)return 0;var b=ea.get(a);void 0===b&&(da=b=da+1|0,ea.set(a,b));return b}}:function(a){if(a&&a.a){var b=a.$idHashCode$0;if(void 0!==b)return b;if(m.Object.isSealed(a))return 42;da=b=da+1|0;return a.$idHashCode$0=b}return null===a?0:ua(a)};function x(a){return null===a?Da().W:a}this.__ScalaJSExportsNamespace=aa;
function Ea(){this.Ea=this.eb=void 0;this.ka=this.oa=this.h=null;this.ma=0;this.Ua=null;this.za="";this.A=this.wa=this.xa=void 0;this.name="";this.isRawJSType=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function y(a,b,c){var d=new Ea;d.h={};d.oa=null;d.Ua=a;d.za=b;d.A=f(!1);d.name=c;d.isPrimitive=!0;d.isInstance=f(!1);return d}
function A(a,b,c,d,e,g,h,p){var q=new Ea,u=fa(a);h=h||function(a){return!!(a&&a.a&&a.a.h[u])};p=p||function(a,b){return!!(a&&a.a&&a.a.ma===b&&a.a.ka.h[u])};q.Ea=g;q.h=d;q.za="L"+c+";";q.A=p;q.name=c;q.isInterface=b;q.isRawJSType=!!e;q.isInstance=h;return q}
function Fa(a){function b(a){if("number"===typeof a){this.g=Array(a);for(var b=0;b<a;b++)this.g[b]=e}else this.g=a}var c=new Ea,d=a.Ua,e="longZero"==d?Da().W:d;b.prototype=new B;b.prototype.a=c;var d="["+a.za,g=a.ka||a,h=a.ma+1;c.eb=b;c.Ea=Ga;c.h={b:1,nb:1,e:1};c.oa=a;c.ka=g;c.ma=h;c.Ua=null;c.za=d;c.xa=void 0;c.wa=void 0;c.A=void 0;c.name=d;c.isPrimitive=!1;c.isInterface=!1;c.isArrayClass=!0;c.isInstance=function(a){return g.A(a,h)};return c}
function s(a){if(!a.xa){var b=new Ha;b.Aa=a;a.xa=b}return a.xa}function Ia(a){a.wa||(a.wa=Fa(a));return a.wa}Ea.prototype.getFakeInstance=function(){return this===ka?"some string":this===qa?!1:this===la||this===ma||this===na||this===oa||this===pa?0:this===sa?Da().W:this===ra?void 0:{a:this}};Ea.prototype.getSuperclass=function(){return this.Ea?s(this.Ea):null};Ea.prototype.getComponentType=function(){return this.oa?s(this.oa):null};
Ea.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=Ia(b);return ga(b,a)};var Ja=y(!1,"Z","boolean"),Ka=y(0,"C","char"),La=y(0,"B","byte"),Ma=y(0,"S","short"),Na=y(0,"I","int"),Oa=y("longZero","J","long"),Pa=y(0,"F","float"),Qa=y(0,"D","double");Ja.A=r(Ja);Ka.A=r(Ka);La.A=r(La);Ma.A=r(Ma);Na.A=r(Na);Oa.A=r(Oa);Pa.A=r(Pa);Qa.A=r(Qa);function Ra(){}function B(){}B.prototype=Ra.prototype;Ra.prototype.d=function(){return this};Ra.prototype.q=function(a){return this===a};Ra.prototype.i=function(){var a=Sa(ja(this)),b=(+(this.t()>>>0)).toString(16);return a+"@"+b};Ra.prototype.t=function(){return ya(this)};Ra.prototype.toString=function(){return this.i()};var Ga=A({b:0},!1,"java.lang.Object",{b:1},void 0,void 0,function(a){return null!==a},function(a,b){var c=a&&a.a;if(c){var d=c.ma||0;return!(d<b)&&(d>b||!c.ka.isPrimitive)}return!1});
Ra.prototype.a=Ga;function Ta(a,b){for(var c=a.ha(),d=b.ha();c.r()&&d.r();)if(!C(D(),c.B(),d.B()))return!1;return!c.r()&&!d.r()}function Ua(a,b,c,d,e){var g=a.ha();a=Va(new E,g,Wa(function(){return function(a){if(null!==a){var b=a.O;a=a.H;Xa||(Xa=(new Ya).d());return""+(""+Za(w(),b)+" -\x3e ")+a}throw(new H).D(a);}}(a)));return $a(a,b,c,d,e)}
function $a(a,b,c,d,e){var g=ab();bb(b.v,c);a.Z(Wa(function(a,b,c,d){return function(a){if(b.c)cb(c,a),b.c=!1;else return bb(c.v,d),cb(c,a)}}(a,g,b,d)));bb(b.v,e);return b}function db(a,b){a:b:for(;;){if(!b.u()){a.Ia(fb());b=gb();continue b}break a}}function hb(a,b){b&&b.a&&b.a.h.Db?db(a,b):b.Z(Wa(function(a){return function(b){return a.Ia(b)}}(a)));return a}var ib=A({Kb:0},!0,"scala.collection.mutable.HashEntry",{Kb:1});
function jb(a){for(var b=-1+a.p.g.length|0;null===a.p.g[b]&&0<b;)b=-1+b|0;return b}function kb(a,b){var c=I(J(),b);return lb(a,b,mb(a,c))}function lb(a,b,c){for(a=a.p.g[c];;)if(null!==a?(c=a.R,c=!C(D(),c,b)):c=!1,c)a=a.y;else break;return a}function nb(a,b){if(null!==a.G){var c=a.G,d=b>>5;c.g[d]=1+c.g[d]|0}}function ob(a,b){if(null!==a.G){var c=a.G,d=b>>5;c.g[d]=-1+c.g[d]|0}}
function mb(a,b){var c=-1+a.p.g.length|0,d=a.Ra;pb||(pb=(new qb).d());var e;e=n(-1640532531,b);rb();e=n(-1640532531,e<<24|16711680&e<<8|65280&(e>>>8|0)|e>>>24|0);d=d%32|0;return(e>>>d|0|e<<(32-d|0))>>(32-sb(rb(),c)|0)&c}
function tb(a,b,c){var d=I(J(),b),d=mb(a,d),e=lb(a,b,d);if(null!==e)a=e;else{b=(new ub).Ba(b,c);b.y=a.p.g[d];a.p.g[d]=b;a.C=1+a.C|0;nb(a,d);if(a.C>a.Ga){b=n(2,a.p.g.length);c=a.p;a.p=ga(Ia(ib),[b]);if(null!==a.G)if(d=1+(a.p.g.length>>5)|0,a.G.g.length!==d)a.G=ga(Ia(Na),[d]);else{vb||(vb=(new wb).d());for(var d=a.G,e=d.g.length,g=0;g!==e;)d.g[g]=0,g=1+g|0}for(d=-1+c.g.length|0;0<=d;){for(e=c.g[d];null!==e;){var g=e.R,g=I(J(),g),g=mb(a,g),h=e.y;e.y=a.p.g[g];a.p.g[g]=e;e=h;nb(a,g)}d=-1+d|0}a.Ga=xb(yb(),
a.va,b)}a=null}return a}function zb(){this.$d=this.fb=this.Nb=this.Yd=this.Xd=this.Wd=this.Vd=this.Ud=this.Qd=this.Pd=this.Md=this.Ld=this.Kd=this.Jd=this.Id=this.Hd=this.Gd=this.Fd=this.Cd=this.Bd=this.Ad=this.yd=this.xd=this.wd=this.vd=this.ud=this.sd=this.rd=this.md=null;this.I=0}zb.prototype=new B;zb.prototype.constructor=zb;zb.prototype.d=function(){return this};function Ab(){var a=Bb();0===(134217728&a.I)&&0===(134217728&a.I)&&(a.fb=Cb(a).document,a.I|=134217728);return a.fb}
function Cb(a){0===(67108864&a.I)&&0===(67108864&a.I)&&(a.Nb=m,a.I|=67108864);return a.Nb}zb.prototype.a=A({Pb:0},!1,"org.scalajs.dom.package$",{Pb:1,b:1});var Db=void 0;function Bb(){Db||(Db=(new zb).d());return Db}function K(){this.ta=!1;this.ea=null}K.prototype=new B;K.prototype.constructor=K;K.prototype.j=function(a){this.ta=!1;this.ea=Ab().createElement("img");this.ea.onload=function(a){return function(){a.ta=!0}}(this);this.ea.src=a;return this};
K.prototype.a=A({Rb:0},!1,"simplegame.Image",{Rb:1,b:1});function Ha(){this.Aa=null}Ha.prototype=new B;Ha.prototype.constructor=Ha;function Sa(a){return a.Aa.name}Ha.prototype.i=function(){return(this.Aa.isInterface?"interface ":this.Aa.isPrimitive?"":"class ")+Sa(this)};Ha.prototype.a=A({cc:0},!1,"java.lang.Class",{cc:1,b:1});function wb(){this.be=0}wb.prototype=new B;wb.prototype.constructor=wb;wb.prototype.d=function(){return this};wb.prototype.a=A({nc:0},!1,"java.util.Arrays$",{nc:1,b:1});
var vb=void 0;function Ya(){}Ya.prototype=new B;Ya.prototype.constructor=Ya;Ya.prototype.d=function(){return this};Ya.prototype.a=A({uc:0},!1,"scala.Predef$any2stringadd$",{uc:1,b:1});var Xa=void 0;function Eb(){}Eb.prototype=new B;Eb.prototype.constructor=Eb;function Fb(){}Fb.prototype=Eb.prototype;Eb.prototype.Da=function(a,b){var c;c=n(-862048943,b);c=n(461845907,c<<15|c>>>-15|0);return a^c};Eb.prototype.F=function(a,b){var c=this.Da(a,b);return-430675100+n(5,c<<13|c>>>-13|0)|0};
function Gb(a,b,c){var d=(new L).o(0),e=(new L).o(0),g=(new L).o(0),h=(new L).o(1);b.Z(Wa(function(a,b,c,d,e){return function(a){a=I(J(),a);b.c=b.c+a|0;c.c^=a;0!==a&&(e.c=n(e.c,a));d.c=1+d.c|0}}(a,d,e,g,h)));b=a.F(c,d.c);b=a.F(b,e.c);b=a.Da(b,h.c);return a.Y(b,g.c)}function Hb(a){var b=Ib(),c=a.J();if(0===c)return a=a.L(),va(w(),a);for(var d=-889275714,e=0;e<c;)d=b.F(d,I(J(),a.K(e))),e=1+e|0;return b.Y(d,c)}
Eb.prototype.Y=function(a,b){var c=a^b,c=n(-2048144789,c^(c>>>16|0)),c=c^(c>>>13|0),c=n(-1028477387,c);return c^=c>>>16|0};function Jb(a,b,c){var d=(new L).o(0);c=(new L).o(c);b.Z(Wa(function(a,b,c){return function(d){c.c=a.F(c.c,I(J(),d));b.c=1+b.c|0}}(a,d,c)));return a.Y(c.c,d.c)}function qb(){}qb.prototype=new B;qb.prototype.constructor=qb;qb.prototype.d=function(){return this};qb.prototype.a=A({xc:0},!1,"scala.util.hashing.package$",{xc:1,b:1});var pb=void 0;function Kb(){this.Ma=null}
Kb.prototype=new B;Kb.prototype.constructor=Kb;Kb.prototype.d=function(){Lb=this;this.Ma=(new M).d();return this};Kb.prototype.a=A({Dc:0},!1,"scala.collection.Iterator$",{Dc:1,b:1});var Lb=void 0;function Mb(){Lb||(Lb=(new Kb).d());return Lb}function Nb(){}Nb.prototype=new B;Nb.prototype.constructor=Nb;function Ob(){}Ob.prototype=Nb.prototype;function Pb(){Qb||(Qb=(new Rb).d());var a;Sb||(Sb=(new Tb).d());a=Sb;return(new Ub).d().Wa(a).rb()}function Vb(){}Vb.prototype=new B;
Vb.prototype.constructor=Vb;Vb.prototype.d=function(){return this};function Wb(){yb();var a=15,a=a|a>>>1|0,a=a|a>>>2|0,a=a|a>>>4|0,a=a|a>>>8|0;return 1+(a|a>>>16|0)|0}
function xb(a,b,c){c=(new N).o(c);b=(new N).o(b);a=c.l;var d=c.n,e=b.l,g=b.n;b=65535&a;a=a>>>16|0;c=65535&d;var d=d>>>16|0,h=65535&e,e=e>>>16|0,p=65535&g,g=g>>>16|0,q=n(b,h),u;u=(q>>>16|0)+n(a,h)|0;var t=u>>>16|0;u=(65535&u)+n(b,e)|0;var t=t+(u>>>16|0)|0,F=t>>>16|0,t=(65535&t)+n(c,h)|0,F=F+(t>>>16|0)|0,t=(65535&t)+n(a,e)|0,F=F+(t>>>16|0)|0,t=(65535&t)+n(b,p)|0,F=((((F+(t>>>16|0)|0)+n(d,h)|0)+n(c,e)|0)+n(a,p)|0)+n(b,g)|0;c=(new N).f(65535&q|u<<16,65535&t|F<<16);b=(new N).f(1E3,0);a=c.l;h=c.n;c=b.l;
d=b.n;if(0===(c|d))throw(new Xb).j("/ by zero");h===a>>31?b=d===c>>31?-2147483648===a&&-1===c?(new N).f(-2147483648,0):(new N).o(a/c|0):-2147483648===a&&-2147483648===c&&0===d?Da().bb:Da().W:(b=0>h,p=a,e=h,b&&(p=-a|0,e=0!==a?~h:-h|0),h=p,a=0>d,g=c,p=d,a&&(g=-c|0,p=0!==c?~d:-d|0),c=g,d=p,0===(-2097152&e)?0===(-2097152&d)?(c=(4294967296*e+ +(h>>>0))/(4294967296*d+ +(c>>>0)),c=(new N).f(c|0,c/4294967296|0)):c=Da().W:0===d&&0===(c&(-1+c|0))?(c=31-ca(c)|0,c=0===c?(new N).f(h,e):(new N).f(h>>>c|0|e<<(-c|
0),e>>>c|0)):0===c&&0===(d&(-1+d|0))?(c=31-ca(d)|0,c=(new N).f(e>>>c|0,0)):c=Yb(h,e,c,d,0),b===a?b=c:(b=c.l,a=c.n,b=(new N).f(-b|0,0!==b?~a:-a|0)));return b.l}Vb.prototype.a=A({Sc:0},!1,"scala.collection.mutable.HashTable$",{Sc:1,b:1});var Zb=void 0;function yb(){Zb||(Zb=(new Vb).d());return Zb}function $b(){this.da=!1;this.ib=this.Wb=this.Ca=this.la=null;this.Ka=!1;this.ob=this.kb=0}$b.prototype=new B;$b.prototype.constructor=$b;
$b.prototype.d=function(){ac=this;this.la=(this.da=!!(m.ArrayBuffer&&m.Int32Array&&m.Float32Array&&m.Float64Array))?new m.ArrayBuffer(8):null;this.Ca=this.da?new m.Int32Array(this.la,0,2):null;this.Wb=this.da?new m.Float32Array(this.la,0,2):null;this.ib=this.da?new m.Float64Array(this.la,0,1):null;if(this.da)this.Ca[0]=16909060,a=1===((new m.Int8Array(this.la,0,8))[0]|0);else var a=!0;this.kb=(this.Ka=a)?0:1;this.ob=this.Ka?1:0;return this};
function wa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.da)a.ib[0]=b,c=bc(cc((new N).o(a.Ca[a.kb]|0)),dc((new N).f(-1,0),(new N).o(a.Ca[a.ob]|0)));else{if(b!==b)var c=!1,d=2047,e=+m.Math.pow(2,51);else if(Infinity===b||-Infinity===b)c=0>b,d=2047,e=0;else if(0===b)c=-Infinity===1/b,e=d=0;else{var g=(c=0>b)?-b:b;if(g>=+m.Math.pow(2,-1022)){var d=+m.Math.pow(2,52),e=+m.Math.log(g)/0.6931471805599453,e=+m.Math.floor(e)|0,e=1023>e?e:1023,h=g/+m.Math.pow(2,e)*d,g=+m.Math.floor(h),h=h-g,g=0.5>
h?g:0.5<h?1+g:0!==g%2?1+g:g;2<=g/d&&(e=1+e|0,g=1);1023<e?(e=2047,g=0):(e=1023+e|0,g-=d);d=e;e=g}else d=g/+m.Math.pow(2,-1074),e=+m.Math.floor(d),g=d-e,d=0,e=0.5>g?e:0.5<g?1+e:0!==e%2?1+e:e}e=+e;g=e|0;c=bc(cc((new N).o((c?-2147483648:0)|(d|0)<<20|e/4294967296|0)),dc((new N).f(-1,0),(new N).o(g)))}return c.l^c.n}$b.prototype.a=A({$c:0},!1,"scala.scalajs.runtime.Bits$",{$c:1,b:1});var ac=void 0;function xa(){ac||(ac=(new $b).d());return ac}function ec(){this.td=null;this.I=!1}ec.prototype=new B;
ec.prototype.constructor=ec;ec.prototype.d=function(){return this};function Za(a,b){return null===b?"null":ia(b)}function fc(a){if(0===(-65536&a)){var b=m.String;return b.fromCharCode.apply(b,[a])}if(0>a||1114111<a)throw(new gc).d();a=-65536+a|0;b=m.String;return b.fromCharCode.apply(b,[55296|a>>10,56320|1023&a])}function va(a,b){for(var c=0,d=1,e=-1+(b.length|0)|0;0<=e;)c=c+n(65535&(b.charCodeAt(e)|0),d)|0,d=n(31,d),e=-1+e|0;return c}
ec.prototype.a=A({bd:0},!1,"scala.scalajs.runtime.RuntimeString$",{bd:1,b:1});var hc=void 0;function w(){hc||(hc=(new ec).d());return hc}function ic(){}ic.prototype=new B;ic.prototype.constructor=ic;ic.prototype.d=function(){return this};function jc(a,b){return kc(b)?b.Q:b}function lc(a,b){return b&&b.a&&b.a.h.ba?b:(new mc).D(b)}ic.prototype.a=A({cd:0},!1,"scala.scalajs.runtime.package$",{cd:1,b:1});var nc=void 0;function oc(){nc||(nc=(new ic).d());return nc}function pc(){}pc.prototype=new B;
pc.prototype.constructor=pc;pc.prototype.d=function(){return this};function C(a,b,c){return b===c?!0:qc(b)?qc(c)?rc(b,c):sc(c)?"number"===typeof b?+b===c.m:v(b)?tc(x(b),(new N).o(c.m)):null===b?null===c:ta(b,c):null===b?null===c:ta(b,c):sc(b)?sc(c)?b.m===c.m:qc(c)?"number"===typeof c?+c===b.m:v(c)?tc(x(c),(new N).o(b.m)):null===c?null===b:ta(c,b):null===b&&null===c:null===b?null===c:ta(b,c)}
function rc(a,b){if("number"===typeof a){var c=+a;if("number"===typeof b)return c===+b;if(v(b)){var d=x(b);return c===uc(d)}return b&&b.a&&b.a.h.vc?b.q(c):!1}return v(a)?(c=x(a),v(b)?(d=x(b),tc(c,d)):"number"===typeof b?uc(c)===+b:b&&b.a&&b.a.h.vc?b.q(c):!1):null===a?null===b:ta(a,b)}pc.prototype.a=A({fd:0},!1,"scala.runtime.BoxesRunTime$",{fd:1,b:1});var vc=void 0;function D(){vc||(vc=(new pc).d());return vc}function wc(){}wc.prototype=new B;wc.prototype.constructor=wc;wc.prototype.d=function(){return this};
function I(a,b){if(null===b)return 0;if(qc(b)){if("number"===typeof b){var c=+b;return xc(O(),c)}if(v(b))return c=x(b),yc(O(),c)}return ua(b)}function zc(a){J();return a.S().ya((new P).d(),a.L()+"(",",",")").v.z}wc.prototype.a=A({jd:0},!1,"scala.runtime.ScalaRunTime$",{jd:1,b:1});var Ac=void 0;function J(){Ac||(Ac=(new wc).d());return Ac}function Bc(){}Bc.prototype=new B;Bc.prototype.constructor=Bc;k=Bc.prototype;k.d=function(){return this};
k.Da=function(a,b){var c;c=n(-862048943,b);c=n(461845907,c<<15|c>>>-15|0);return a^c};function xc(a,b){var c=za(b);if(c===b)return c;c=Cc(Da(),b);return uc(c)===b?c.l^c.n:wa(xa(),b)}function Dc(a,b){if(null===b)return 0;if("number"===typeof b)return xc(0,+b);if(v(b)){var c=x(b);return yc(0,c)}return ua(b)}k.F=function(a,b){var c=this.Da(a,b);return-430675100+n(5,c<<13|c>>>-13|0)|0};function yc(a,b){var c=b.l,d=b.n;return d===c>>31?c:c^d}
k.Y=function(a,b){var c=a^b,c=n(-2048144789,c^(c>>>16|0)),c=c^(c>>>13|0),c=n(-1028477387,c);return c^=c>>>16|0};k.a=A({ld:0},!1,"scala.runtime.Statics$",{ld:1,b:1});var Ec=void 0;function O(){Ec||(Ec=(new Bc).d());return Ec}function Fc(){}Fc.prototype=new B;Fc.prototype.constructor=Fc;Fc.prototype.d=function(){return this};
function Gc(a,b,c){b.c=Hc((new Q).f((a.width|0)/2|0,(a.height|0)/2|0),b.c.V);c.c=Ic(new Jc,(new Q).f(R().N+za(+m.Math.random()*(-64+(a.width|0)|0))|0,R().N+za(+m.Math.random()*(-64+(a.height|0)|0))|0))}
function Kc(){var a=Ab().createElement("canvas"),b=a.getContext("2d");a.width=za(0.95*(Cb(Bb()).innerWidth|0));a.height=za(0.95*(Cb(Bb()).innerHeight|0));Ab().body.appendChild(a);var c=(new K).j("images/background.png"),d=(new K).j("images/hero.png"),e=(new K).j("images/monster.png"),g=(new S).D(Hc((new Q).f(0,0),256)),h=(new S).D(Ic(new Jc,(new Q).f(0,0))),p=(new L).o(0),q=Pb();Cb(Bb()).addEventListener("keydown",function(a){return function(b){b=tb(a,b.keyCode|0,!0);null!==b&&(b.m=!0);return a}}(q),
!1);Cb(Bb()).addEventListener("keyup",function(a){return function(b){b=b.keyCode|0;var c=I(J(),b),c=mb(a,c),d=a.p.g[c];if(null!==d){var e=d.R;if(C(D(),e,b))a.p.g[c]=d.y,a.C=-1+a.C|0,ob(a,c);else{for(e=d.y;;){if(null!==e)var g=e.R,g=!C(D(),g,b);else g=!1;if(g)d=e,e=e.y;else break}null!==e&&(d.y=e.y,a.C=-1+a.C|0,ob(a,c))}}return a}}(q),!1);var u=+m.Date.now(),b=Lc(new Mc,function(a,b,c,d,e,g,h,p,q,u){return function(){var rd=+m.Date.now(),z=rd-u.c;Nc();var z=za(g.c.V*(z/1E3)),G=g.c.k;if(null!==G)var eb=
G.w,G=G.x;else throw(new H).D(G);null!==kb(q,37)&&(eb=eb-z|0);null!==kb(q,39)&&(eb=eb+z|0);null!==kb(q,38)&&(G=G-z|0);null!==kb(q,40)&&(G=G+z|0);z=(new Q).f(eb,G);0<=z.w&&(z.w+R().N|0)<=(a.width|0)&&0<=z.x&&(z.x+R().N|0)<=(a.height|0)&&(g.c=Hc(z,g.c.V));g.c.k.w<=(h.c.k.w+R().N|0)&&h.c.k.w<=(g.c.k.w+R().N|0)&&g.c.k.x<=(h.c.k.x+R().N|0)&&h.c.k.x<=(g.c.k.x+R().N|0)&&(p.c=1+p.c|0,Gc(a,g,h));Nc();c.ta&&b.drawImage(c.ea,0,0,a.width|0,a.height|0);d.ta&&b.drawImage(d.ea,g.c.k.w,g.c.k.x);e.ta&&b.drawImage(e.ea,
h.c.k.w,h.c.k.x);b.fillStyle="rgb(250, 250, 250)";b.font="24px Helvetica";b.textAlign="left";b.textBaseline="top";b.fillText("Goblins caught: "+p.c,32,32);u.c=rd}}(a,b,c,d,e,g,h,p,q,Oc(u)));Gc(a,g,h);Cb(Bb()).setInterval(function(a){return function(){return(0,a.pa)()}}(b),1)}Fc.prototype.main=function(){Kc()};Fc.prototype.a=A({Sb:0},!1,"simplegame.SimpleCanvasGame$",{Sb:1,b:1,Qe:1});var Pc=void 0;function Nc(){Pc||(Pc=(new Fc).d());return Pc}aa.simplegame=aa.simplegame||{};
aa.simplegame.SimpleCanvasGame=Nc;function Qc(){}Qc.prototype=new B;Qc.prototype.constructor=Qc;function Rc(){}Rc.prototype=Qc.prototype;function qc(a){return!!(a&&a.a&&a.a.h.aa||"number"===typeof a)}function T(){this.Te=this.Vb=this.sb=null}T.prototype=new B;T.prototype.constructor=T;function Sc(){}Sc.prototype=T.prototype;
T.prototype.hb=function(){if(void 0===m.Error.captureStackTrace){try{var a={}.undef()}catch(b){if(a=lc(oc(),b),null!==a)if(kc(a))a=a.Q;else throw jc(oc(),a);else throw b;}this.stackdata=a}else m.Error.captureStackTrace(this),this.stackdata=this;return this};T.prototype.jb=function(){return this.sb};T.prototype.i=function(){var a=Sa(ja(this)),b=this.jb();return null===b?a:a+": "+b};T.prototype.$=function(a,b){this.sb=a;this.Vb=b;this.hb();return this};
function Tc(){this.Xc=this.pb=this.Sa=this.Ze=this.Ve=this.fe=this.Ue=this.Zd=0}Tc.prototype=new Fb;Tc.prototype.constructor=Tc;Tc.prototype.d=function(){Uc=this;this.Sa=va(w(),"Seq");this.pb=va(w(),"Map");this.Xc=va(w(),"Set");return this};function Vc(a){var b=Ib();if(a&&a.a&&a.a.h.Lc){for(var c=0,d=b.Sa;!a.u();)Wc(),a=gb(),d=b.F(d,I(J(),void 0)),c=1+c|0;b=b.Y(d,c)}else b=Jb(b,a,b.Sa);return b}Tc.prototype.a=A({wc:0},!1,"scala.util.hashing.MurmurHash3$",{wc:1,je:1,b:1});var Uc=void 0;
function Ib(){Uc||(Uc=(new Tc).d());return Uc}function Xc(){}Xc.prototype=new Ob;Xc.prototype.constructor=Xc;function Yc(){}Yc.prototype=Xc.prototype;function Zc(){}Zc.prototype=new B;Zc.prototype.constructor=Zc;function $c(){}$c.prototype=Zc.prototype;Zc.prototype.i=f("\x3cfunction0\x3e");function ad(){}ad.prototype=new B;ad.prototype.constructor=ad;function bd(){}bd.prototype=ad.prototype;ad.prototype.i=f("\x3cfunction1\x3e");function cd(){this.c=!1}cd.prototype=new B;cd.prototype.constructor=cd;
cd.prototype.i=function(){return""+this.c};function ab(){var a=new cd;a.c=!0;return a}cd.prototype.a=A({dd:0},!1,"scala.runtime.BooleanRef",{dd:1,b:1,e:1});var ra=A({ed:0},!1,"scala.runtime.BoxedUnit",{ed:1,b:1,e:1},void 0,void 0,function(a){return void 0===a});function dd(){this.c=0}dd.prototype=new B;dd.prototype.constructor=dd;function Oc(a){var b=new dd;b.c=a;return b}dd.prototype.i=function(){return""+this.c};dd.prototype.a=A({gd:0},!1,"scala.runtime.DoubleRef",{gd:1,b:1,e:1});
function L(){this.c=0}L.prototype=new B;L.prototype.constructor=L;L.prototype.i=function(){return""+this.c};L.prototype.o=function(a){this.c=a;return this};L.prototype.a=A({hd:0},!1,"scala.runtime.IntRef",{hd:1,b:1,e:1});function S(){this.c=null}S.prototype=new B;S.prototype.constructor=S;S.prototype.i=function(){return Za(w(),this.c)};S.prototype.D=function(a){this.c=a;return this};S.prototype.a=A({id:0},!1,"scala.runtime.ObjectRef",{id:1,b:1,e:1});function ed(){this.N=0}ed.prototype=new B;
ed.prototype.constructor=ed;ed.prototype.d=function(){this.N=32;return this};ed.prototype.a=A({Qb:0},!1,"simplegame.Hero$",{Qb:1,b:1,s:1,e:1});var fd=void 0;function R(){fd||(fd=(new ed).d());return fd}var qa=A({ac:0},!1,"java.lang.Boolean",{ac:1,b:1,e:1,E:1},void 0,void 0,function(a){return"boolean"===typeof a});function U(){this.m=0}U.prototype=new B;U.prototype.constructor=U;U.prototype.q=function(a){return sc(a)?this.m===a.m:!1};U.prototype.i=function(){return m.String.fromCharCode(this.m)};
function gd(a){var b=new U;b.m=a;return b}U.prototype.t=function(){return this.m};function sc(a){return!!(a&&a.a&&a.a.h.mb)}U.prototype.a=A({mb:0},!1,"java.lang.Character",{mb:1,b:1,e:1,E:1});function hd(){T.call(this)}hd.prototype=new Sc;hd.prototype.constructor=hd;function id(){}id.prototype=hd.prototype;function jd(){this.Od=null;this.qd=this.Nd=this.Dd=this.Ed=0}jd.prototype=new B;jd.prototype.constructor=jd;jd.prototype.d=function(){return this};
function sb(a,b){var c=b-(1431655765&b>>1)|0,c=(858993459&c)+(858993459&c>>2)|0;return n(16843009,252645135&(c+(c>>4)|0))>>24}jd.prototype.a=A({ic:0},!1,"java.lang.Integer$",{ic:1,b:1,s:1,e:1});var kd=void 0;function rb(){kd||(kd=(new jd).d());return kd}function ld(){}ld.prototype=new Yc;ld.prototype.constructor=ld;function md(){}md.prototype=ld.prototype;function Mc(){this.pa=null}Mc.prototype=new $c;Mc.prototype.constructor=Mc;function Lc(a,b){a.pa=b;return a}
Mc.prototype.a=A({Yc:0},!1,"scala.scalajs.runtime.AnonFunction0",{Yc:1,Re:1,b:1,zd:1});function nd(){this.pa=null}nd.prototype=new bd;nd.prototype.constructor=nd;nd.prototype.P=function(a){return(0,this.pa)(a)};function Wa(a){var b=new nd;b.pa=a;return b}nd.prototype.a=A({Zc:0},!1,"scala.scalajs.runtime.AnonFunction1",{Zc:1,Se:1,b:1,Ja:1});function od(){this.nd=this.pd=this.od=this.Td=this.Sd=this.Rd=0;this.$a=this.ab=this.bb=this.Tb=this.W=null}od.prototype=new B;od.prototype.constructor=od;
od.prototype.d=function(){pd=this;this.W=(new N).f(0,0);this.Tb=(new N).f(1,0);this.bb=(new N).f(-1,-1);this.ab=(new N).f(0,-2147483648);this.$a=(new N).f(-1,2147483647);return this};function Cc(a,b){if(b!==b)return a.W;if(-9223372036854775E3>b)return a.ab;if(9223372036854775E3<=b)return a.$a;var c=0>b,d=c?-b:b,e=d|0,d=d/4294967296|0;return c?(new N).f(-e|0,0!==e?~d:-d|0):(new N).f(e,d)}od.prototype.a=A({ad:0},!1,"scala.scalajs.runtime.RuntimeLong$",{ad:1,b:1,s:1,e:1});var pd=void 0;
function Da(){pd||(pd=(new od).d());return pd}
var ka=A({Ub:0},!1,"java.lang.String",{Ub:1,b:1,e:1,lb:1,E:1},void 0,void 0,function(a){return"string"===typeof a}),la=A({bc:0},!1,"java.lang.Byte",{bc:1,aa:1,b:1,e:1,E:1},void 0,void 0,function(a){return a<<24>>24===a&&1/a!==1/-0}),pa=A({dc:0},!1,"java.lang.Double",{dc:1,aa:1,b:1,e:1,E:1},void 0,void 0,function(a){return"number"===typeof a}),oa=A({ec:0},!1,"java.lang.Float",{ec:1,aa:1,b:1,e:1,E:1},void 0,void 0,function(a){return"number"===typeof a}),na=A({hc:0},!1,"java.lang.Integer",{hc:1,aa:1,
b:1,e:1,E:1},void 0,void 0,function(a){return(a|0)===a&&1/a!==1/-0}),sa=A({jc:0},!1,"java.lang.Long",{jc:1,aa:1,b:1,e:1,E:1},void 0,void 0,function(a){return v(a)});function sd(){T.call(this)}sd.prototype=new id;sd.prototype.constructor=sd;function V(){}V.prototype=sd.prototype;var ma=A({kc:0},!1,"java.lang.Short",{kc:1,aa:1,b:1,e:1,E:1},void 0,void 0,function(a){return a<<16>>16===a&&1/a!==1/-0});function W(){this.z=null}W.prototype=new B;W.prototype.constructor=W;
function bb(a,b){a.z=""+a.z+(null===b?"null":b);return a}W.prototype.i=function(){return this.z};W.prototype.o=function(){W.prototype.j.call(this,"");return this};W.prototype.j=function(a){this.z=a;return this};W.prototype.a=A({lc:0},!1,"java.lang.StringBuilder",{lc:1,b:1,lb:1,ce:1,e:1});function X(){}X.prototype=new B;X.prototype.constructor=X;function td(){}td.prototype=X.prototype;X.prototype.u=function(){return!this.r()};X.prototype.i=function(){return(this.r()?"non-empty":"empty")+" iterator"};
X.prototype.Z=function(a){for(;this.r();)a.P(this.B())};X.prototype.ya=function(a,b,c,d){return $a(this,a,b,c,d)};function ub(){this.y=this.m=this.R=null}ub.prototype=new B;ub.prototype.constructor=ub;function ud(a){return"(kv: "+a.R+", "+a.m+")"+(null!==a.y?" -\x3e "+ud(a.y):"")}ub.prototype.Ba=function(a,b){this.R=a;this.m=b;return this};ub.prototype.i=function(){return ud(this)};ub.prototype.a=A({Pc:0},!1,"scala.collection.mutable.DefaultEntry",{Pc:1,b:1,Kb:1,s:1,e:1});
function N(){this.n=this.l=0}N.prototype=new Rc;N.prototype.constructor=N;function bc(a,b){return(new N).f(a.l|b.l,a.n|b.n)}k=N.prototype;k.q=function(a){return v(a)?this.l===a.l&&this.n===a.n:!1};
function Yb(a,b,c,d,e){var g=(0!==d?ca(d):32+ca(c)|0)-(0!==b?ca(b):32+ca(a)|0)|0,h=g;if(0===h)var p=c,h=d;else 32>h?(p=c<<h,h=c>>>(-h|0)|0|d<<h):(p=0,h=c<<h);var q=p,u=h,p=a,h=b;for(a=b=0;0<=g&&0!==(-2097152&h);){var t=p,F=h,Pd=q,qd=u;if(F===qd?(-2147483648^t)>=(-2147483648^Pd):(-2147483648^F)>=(-2147483648^qd))t=p,p=t-q|0,h=(h-u|0)+((-2147483648^t)<(-2147483648^p)?-1:0)|0,32>g?b|=1<<g:a|=1<<g;g=-1+g|0;t=u>>>1|0;q=q>>>1|0|u<<-1;u=t}g=h;if(g===d?(-2147483648^p)>=(-2147483648^c):(-2147483648^g)>=(-2147483648^
d))g=4294967296*h+ +(p>>>0),c=4294967296*d+ +(c>>>0),1!==e&&(d=g/c,q=b,b=u=q+(d|0)|0,a=(a+(d/4294967296|0)|0)+((-2147483648^u)<(-2147483648^q)?1:0)|0),0!==e&&(c=g%c,p=c|0,h=c/4294967296|0);return 0===e?(new N).f(b,a):1===e?(new N).f(p,h):[b,a,p,h]}k.i=function(){var a=this.l,b=this.n;return b===a>>31?""+a:0>b?"-"+vd(-a|0,0!==a?~b:-b|0):vd(a,b)};k.f=function(a,b){this.l=a;this.n=b;return this};function dc(a,b){return(new N).f(a.l&b.l,a.n&b.n)}function cc(a){return(new N).f(0,a.l<<32)}
k.o=function(a){N.prototype.f.call(this,a,a>>31);return this};function uc(a){var b=a.l;a=a.n;return 0>a?-(4294967296*+((0!==b?~a:-a|0)>>>0)+ +((-b|0)>>>0)):4294967296*a+ +(b>>>0)}k.t=function(){return this.l^this.n};function vd(a,b){if(0===(-2097152&b))return""+(4294967296*b+ +(a>>>0));var c=Yb(a,b,1E9,0,2),d=""+(c["2"]|0);return""+(4294967296*(c["1"]|0)+ +((c["0"]|0)>>>0))+"000000000".substring(d.length|0)+d}function tc(a,b){return a.l===b.l&&a.n===b.n}function v(a){return!!(a&&a.a&&a.a.h.Mb)}
k.a=A({Mb:0},!1,"scala.scalajs.runtime.RuntimeLong",{Mb:1,aa:1,b:1,e:1,E:1});function wd(){this.k=null;this.V=0}wd.prototype=new B;wd.prototype.constructor=wd;k=wd.prototype;k.L=f("Hero");k.J=f(2);k.q=function(a){if(this===a)return!0;if(a&&a.a&&a.a.h.Xa){var b=this.k,c=a.k;return(null===b?null===c:b.q(c))?this.V===a.V:!1}return!1};k.K=function(a){switch(a){case 0:return this.k;case 1:return this.V;default:throw(new Y).j(""+a);}};function Hc(a,b){var c=new wd;c.k=a;c.V=b;return c}k.i=function(){return zc(this)};
k.t=function(){var a=-889275714,a=O().F(a,Dc(O(),this.k)),a=O().F(a,this.V);return O().Y(a,2)};k.S=function(){return Z(this)};k.a=A({Xa:0},!1,"simplegame.Hero",{Xa:1,b:1,ca:1,M:1,s:1,e:1});function Jc(){this.k=null}Jc.prototype=new B;Jc.prototype.constructor=Jc;k=Jc.prototype;k.L=f("Monster");k.J=f(1);function Ic(a,b){a.k=b;return a}k.q=function(a){if(this===a)return!0;if(a&&a.a&&a.a.h.Ya){var b=this.k;a=a.k;return null===b?null===a:b.q(a)}return!1};
k.K=function(a){switch(a){case 0:return this.k;default:throw(new Y).j(""+a);}};k.i=function(){return zc(this)};k.t=function(){return Hb(this)};k.S=function(){return Z(this)};k.a=A({Ya:0},!1,"simplegame.Monster",{Ya:1,b:1,ca:1,M:1,s:1,e:1});function Q(){this.x=this.w=0}Q.prototype=new B;Q.prototype.constructor=Q;k=Q.prototype;k.L=f("Position");k.J=f(2);k.q=function(a){return this===a?!0:a&&a.a&&a.a.h.Za?this.w===a.w&&this.x===a.x:!1};
k.K=function(a){switch(a){case 0:return this.w;case 1:return this.x;default:throw(new Y).j(""+a);}};k.f=function(a,b){this.w=a;this.x=b;return this};k.i=function(){return zc(this)};k.t=function(){var a=-889275714,a=O().F(a,this.w),a=O().F(a,this.x);return O().Y(a,2)};k.S=function(){return Z(this)};k.a=A({Za:0},!1,"simplegame.Position",{Za:1,b:1,ca:1,M:1,s:1,e:1});function Xb(){T.call(this)}Xb.prototype=new V;Xb.prototype.constructor=Xb;Xb.prototype.j=function(a){T.prototype.$.call(this,a,null);return this};
Xb.prototype.a=A({$b:0},!1,"java.lang.ArithmeticException",{$b:1,ja:1,ia:1,ba:1,b:1,e:1});function gc(){T.call(this)}gc.prototype=new V;gc.prototype.constructor=gc;gc.prototype.d=function(){T.prototype.$.call(this,null,null);return this};gc.prototype.a=A({fc:0},!1,"java.lang.IllegalArgumentException",{fc:1,ja:1,ia:1,ba:1,b:1,e:1});function Y(){T.call(this)}Y.prototype=new V;Y.prototype.constructor=Y;Y.prototype.j=function(a){T.prototype.$.call(this,a,null);return this};
Y.prototype.a=A({gc:0},!1,"java.lang.IndexOutOfBoundsException",{gc:1,ja:1,ia:1,ba:1,b:1,e:1});function xd(){T.call(this)}xd.prototype=new V;xd.prototype.constructor=xd;xd.prototype.j=function(a){T.prototype.$.call(this,a,null);return this};xd.prototype.a=A({mc:0},!1,"java.lang.UnsupportedOperationException",{mc:1,ja:1,ia:1,ba:1,b:1,e:1});function $(){T.call(this)}$.prototype=new V;$.prototype.constructor=$;$.prototype.j=function(a){T.prototype.$.call(this,a,null);return this};
$.prototype.a=A({oc:0},!1,"java.util.NoSuchElementException",{oc:1,ja:1,ia:1,ba:1,b:1,e:1});function H(){T.call(this);this.qb=this.qa=null;this.La=!1}H.prototype=new V;H.prototype.constructor=H;H.prototype.jb=function(){if(!this.La&&!this.La){var a;if(null===this.qa)a="null";else try{a=ia(this.qa)+" ("+("of class "+Sa(ja(this.qa)))+")"}catch(b){if(null!==lc(oc(),b))a="an instance of class "+Sa(ja(this.qa));else throw b;}this.qb=a;this.La=!0}return this.qb};
H.prototype.D=function(a){this.qa=a;T.prototype.$.call(this,null,null);return this};H.prototype.a=A({qc:0},!1,"scala.MatchError",{qc:1,ja:1,ia:1,ba:1,b:1,e:1});function yd(){}yd.prototype=new B;yd.prototype.constructor=yd;function zd(){}zd.prototype=yd.prototype;function E(){this.gb=this.Ha=null}E.prototype=new td;E.prototype.constructor=E;E.prototype.B=function(){return this.gb.P(this.Ha.B())};function Va(a,b,c){if(null===b)throw jc(oc(),null);a.Ha=b;a.gb=c;return a}E.prototype.r=function(){return this.Ha.r()};
E.prototype.a=A({Ec:0},!1,"scala.collection.Iterator$$anon$11",{Ec:1,ra:1,b:1,sa:1,U:1,T:1});function M(){}M.prototype=new td;M.prototype.constructor=M;M.prototype.d=function(){return this};M.prototype.B=function(){throw(new $).j("next on empty iterator");};M.prototype.r=f(!1);M.prototype.a=A({Fc:0},!1,"scala.collection.Iterator$$anon$2",{Fc:1,ra:1,b:1,sa:1,U:1,T:1});function Ad(){this.Ta=null}Ad.prototype=new td;Ad.prototype.constructor=Ad;
Ad.prototype.B=function(){if(this.r())Wc(),this.Ta=gb();else return Mb().Ma.B()};Ad.prototype.r=function(){return!this.Ta.u()};Ad.prototype.a=A({Gc:0},!1,"scala.collection.LinearSeqLike$$anon$1",{Gc:1,ra:1,b:1,sa:1,U:1,T:1});function Bd(){this.Oa=null;this.fa=0;this.X=null}Bd.prototype=new td;Bd.prototype.constructor=Bd;function Cd(a){var b=new Bd;b.Oa=a.p;b.fa=jb(a);b.X=b.Oa.g[b.fa];return b}
Bd.prototype.B=function(){var a=this.X;for(this.X=this.X.y;null===this.X&&0<this.fa;)this.fa=-1+this.fa|0,this.X=this.Oa.g[this.fa];return a};Bd.prototype.r=function(){return null!==this.X};Bd.prototype.a=A({Tc:0},!1,"scala.collection.mutable.HashTable$$anon$1",{Tc:1,ra:1,b:1,sa:1,U:1,T:1});function Dd(){this.db=this.na=0;this.Ob=null}Dd.prototype=new td;Dd.prototype.constructor=Dd;Dd.prototype.B=function(){var a=this.Ob.K(this.na);this.na=1+this.na|0;return a};
function Z(a){var b=new Dd;b.Ob=a;b.na=0;b.db=a.J();return b}Dd.prototype.r=function(){return this.na<this.db};Dd.prototype.a=A({kd:0},!1,"scala.runtime.ScalaRunTime$$anon$1",{kd:1,ra:1,b:1,sa:1,U:1,T:1});function Ed(){this.H=this.O=null}Ed.prototype=new B;Ed.prototype.constructor=Ed;k=Ed.prototype;k.L=f("Tuple2");k.J=f(2);k.q=function(a){return this===a?!0:a&&a.a&&a.a.h.cb?C(D(),this.O,a.O)&&C(D(),this.H,a.H):!1};
k.K=function(a){a:switch(a){case 0:a=this.O;break a;case 1:a=this.H;break a;default:throw(new Y).j(""+a);}return a};k.Ba=function(a,b){this.O=a;this.H=b;return this};k.i=function(){return"("+this.O+","+this.H+")"};k.t=function(){return Hb(this)};k.S=function(){return Z(this)};k.a=A({cb:0},!1,"scala.Tuple2",{cb:1,b:1,he:1,ca:1,M:1,s:1,e:1});function Fd(){}Fd.prototype=new zd;Fd.prototype.constructor=Fd;k=Fd.prototype;k.d=function(){return this};k.L=f("None");k.J=f(0);
k.K=function(a){throw(new Y).j(""+a);};k.i=f("None");k.t=f(2433880);k.S=function(){return Z(this)};k.a=A({sc:0},!1,"scala.None$",{sc:1,tc:1,b:1,ca:1,M:1,s:1,e:1});var Gd=void 0;function Hd(){this.ua=null}Hd.prototype=new zd;Hd.prototype.constructor=Hd;k=Hd.prototype;k.L=f("Some");k.J=f(1);k.q=function(a){return this===a?!0:a&&a.a&&a.a.h.Pa?C(D(),this.ua,a.ua):!1};k.K=function(a){switch(a){case 0:return this.ua;default:throw(new Y).j(""+a);}};k.i=function(){return zc(this)};
k.D=function(a){this.ua=a;return this};k.t=function(){return Hb(this)};k.S=function(){return Z(this)};k.a=A({Pa:0},!1,"scala.Some",{Pa:1,tc:1,b:1,ca:1,M:1,s:1,e:1});function Rb(){}Rb.prototype=new md;Rb.prototype.constructor=Rb;Rb.prototype.d=function(){return this};Rb.prototype.a=A({Rc:0},!1,"scala.collection.mutable.HashMap$",{Rc:1,we:1,ve:1,ue:1,b:1,s:1,e:1});var Qb=void 0;function Id(){this.ga=this.Na=0;this.Va=null}Id.prototype=new td;Id.prototype.constructor=Id;
Id.prototype.B=function(){this.ga>=this.Na&&Mb().Ma.B();var a=Jd(this.Va,this.ga);this.ga=1+this.ga|0;return a};Id.prototype.r=function(){return this.ga<this.Na};Id.prototype.a=A({Cc:0},!1,"scala.collection.IndexedSeqLike$Elements",{Cc:1,ra:1,b:1,sa:1,U:1,T:1,le:1,s:1,e:1});function mc(){T.call(this);this.Q=null}mc.prototype=new V;mc.prototype.constructor=mc;k=mc.prototype;k.L=f("JavaScriptException");k.J=f(1);k.hb=function(){this.stackdata=this.Q;return this};
k.q=function(a){return this===a?!0:kc(a)?C(D(),this.Q,a.Q):!1};k.K=function(a){switch(a){case 0:return this.Q;default:throw(new Y).j(""+a);}};k.i=function(){return ia(this.Q)};k.D=function(a){this.Q=a;T.prototype.$.call(this,null,null);return this};k.t=function(){return Hb(this)};k.S=function(){return Z(this)};function kc(a){return!!(a&&a.a&&a.a.h.Lb)}k.a=A({Lb:0},!1,"scala.scalajs.js.JavaScriptException",{Lb:1,ja:1,ia:1,ba:1,b:1,e:1,ca:1,M:1,s:1});function Kd(){}Kd.prototype=new B;
Kd.prototype.constructor=Kd;function Ld(){}Ld.prototype=Kd.prototype;function Md(a,b){return a.ya((new P).d(),b,", ",")").v.z}Kd.prototype.ya=function(a,b,c,d){return $a(this,a,b,c,d)};Kd.prototype.Fa=function(){var a=Sa(ja(this)),b;w();b=a;var c=fc(46);b=b.lastIndexOf(c)|0;-1!==b&&(a=a.substring(1+b|0));w();b=a;c=fc(36);b=b.indexOf(c)|0;-1!==b&&(a=a.substring(0,b));return a};function Nd(){}Nd.prototype=new Ld;Nd.prototype.constructor=Nd;function Od(){}Od.prototype=Nd.prototype;function Qd(){}
Qd.prototype=new Od;Qd.prototype.constructor=Qd;function Rd(){}Rd.prototype=Qd.prototype;Qd.prototype.q=function(a){return a&&a.a&&a.a.h.Qa?this.ub(a):!1};Qd.prototype.i=function(){return Md(this,this.Fa()+"(")};function Sd(){}Sd.prototype=new Od;Sd.prototype.constructor=Sd;function Td(){}k=Td.prototype=Sd.prototype;
k.q=function(a){if(a&&a.a&&a.a.h.zc){var b;if(!(b=this===a)&&(b=this.C===a.C))try{for(var c=this.ha(),d=!0;d&&c.r();){var e=c.B();if(null!==e){var g=e.H,h,p=kb(a,e.O),q;null===p?(Gd||(Gd=(new Fd).d()),q=Gd):q=(new Hd).D(p.m);h=q;b:{if(h&&h.a&&h.a.h.Pa){var u=h.ua;if(C(D(),g,u)){d=!0;break b}}d=!1}}else throw(new H).D(e);}b=d}catch(t){if(t&&t.a&&t.a.h.de)b=!1;else throw t;}a=b}else a=!1;return a};k.u=function(){return 0===this.C};k.i=function(){return Md(this,this.Fa()+"(")};
k.ya=function(a,b,c,d){return Ua(this,a,b,c,d)};k.t=function(){var a=Ib();return Gb(a,this,a.pb)};k.Fa=f("Map");function Ud(){}Ud.prototype=new Rd;Ud.prototype.constructor=Ud;function Vd(){}Vd.prototype=Ud.prototype;function Wd(){}Wd.prototype=new Rd;Wd.prototype.constructor=Wd;function Xd(){}k=Xd.prototype=Wd.prototype;k.P=function(a){a|=0;for(var b=this,c=a;!b.u()&&0<c;)b=gb(),c=-1+c|0;if(0>a||b.u())throw(new Y).j(""+a);Wc()};
k.ub=function(a){var b;if(a&&a.a&&a.a.h.Db)if(this===a)b=!0;else{for(b=this;!b.u()&&!a.u()&&C(D(),fb(),fb());)b=gb(),a=gb();b=b.u()&&a.u()}else b=Ta(this,a);return b};k.Z=function(a){for(var b=this;!b.u();)a.P(fb()),b=gb()};k.ha=function(){var a=new Ad;a.Ta=this;return a};k.t=function(){return Vc(this)};k.Fa=f("List");function Tb(){}Tb.prototype=new Xd;Tb.prototype.constructor=Tb;k=Tb.prototype;k.d=function(){return this};function fb(){Wc()}k.L=f("Nil");k.J=f(0);
k.q=function(a){return a&&a.a&&a.a.h.Qa?a.u():!1};function gb(){throw(new xd).j("tail of empty list");}k.u=f(!0);k.K=function(a){throw(new Y).j(""+a);};function Wc(){throw(new $).j("head of empty list");}k.S=function(){return Z(this)};k.a=A({Mc:0},!1,"scala.collection.immutable.Nil$",{Mc:1,Lc:1,yc:1,vb:1,wb:1,b:1,Fb:1,Gb:1,Jb:1,Hb:1,U:1,T:1,Ab:1,Eb:1,zb:1,Ib:1,Bb:1,xb:1,yb:1,Cb:1,M:1,Hc:1,tb:1,Ja:1,Qa:1,Ac:1,Ic:1,Ae:1,Be:1,ze:1,De:1,ge:1,Db:1,qe:1,ca:1,re:1,e:1,s:1});var Sb=void 0;
function Yd(){}Yd.prototype=new Td;Yd.prototype.constructor=Yd;function Zd(){}Zd.prototype=Yd.prototype;Yd.prototype.Wa=function(a){return hb(this,a)};function Ub(){this.va=0;this.p=null;this.Ga=this.C=0;this.G=null;this.Ra=0}Ub.prototype=new Zd;Ub.prototype.constructor=Ub;k=Ub.prototype;k.d=function(){Ub.prototype.Zb.call(this,null);return this};k.P=function(a){var b=kb(this,a);if(null===b)throw(new $).j("key not found: "+a);return b.m};
k.Ia=function(a){var b=tb(this,a.O,a.H);null!==b&&(b.m=a.H);return this};k.Z=function(a){for(var b=this.p,c=jb(this),d=b.g[c];null!==d;){var e=d;a.P((new Ed).Ba(e.R,e.m));for(d=d.y;null===d&&0<c;)c=-1+c|0,d=b.g[c]}};k.rb=function(){return this};k.ha=function(){return Va(new E,Cd(this),Wa(function(){return function(a){return(new Ed).Ba(a.R,a.m)}}(this)))};
k.Zb=function(a){this.va=750;this.p=ga(Ia(ib),[Wb()]);this.C=0;this.Ga=xb(yb(),this.va,Wb());this.G=null;this.Ra=sb(rb(),-1+this.p.g.length|0);null!==a&&(this.va=a.ee(),this.p=a.Xe(),this.C=a.We(),this.Ga=a.Ye(),this.Ra=a.Oe(),this.G=a.Pe());return this};
k.a=A({Qc:0},!1,"scala.collection.mutable.HashMap",{Qc:1,Ee:1,ke:1,vb:1,wb:1,b:1,Fb:1,Gb:1,Jb:1,Hb:1,U:1,T:1,Ab:1,Eb:1,zb:1,Ib:1,Bb:1,xb:1,yb:1,Cb:1,M:1,se:1,zc:1,ne:1,te:1,tb:1,Ja:1,ye:1,Ke:1,Uc:1,Wc:1,rc:1,Le:1,Nc:1,Kc:1,Jc:1,xe:1,Oc:1,pc:1,nb:1,Ge:1,He:1,me:1,s:1,e:1});function P(){this.v=null}P.prototype=new Vd;P.prototype.constructor=P;k=P.prototype;k.d=function(){P.prototype.Xb.call(this,16,"");return this};function Jd(a,b){var c=65535&(a.v.z.charCodeAt(b)|0);return gd(c)}
k.P=function(a){a=65535&(this.v.z.charCodeAt(a|0)|0);return gd(a)};k.ub=function(a){if(a&&a.a&&a.a.h.Bc){var b=$d(this);if(b===$d(a)){for(var c=0;c<b&&C(D(),Jd(this,c),Jd(a,c));)c=1+c|0;a=c===b}else a=!1}else a=Ta(this,a);return a};k.u=function(){return 0===$d(this)};k.Ia=function(a){bb(this.v,m.String.fromCharCode(null===a?0:a.m));return this};k.i=function(){return this.v.z};k.Z=function(a){for(var b=0,c=$d(this);b<c;)a.P(Jd(this,b)),b=1+b|0};k.rb=function(){return this.v.z};
k.ha=function(){var a=new Id;a.Na=this.v.z.length|0;if(null===this)throw jc(oc(),null);a.Va=this;a.ga=0;return a};k.Xb=function(a,b){P.prototype.Yb.call(this,bb((new W).o((b.length|0)+a|0),b));return this};function $d(a){return a.v.z.length|0}k.Yb=function(a){this.v=a;return this};function cb(a,b){bb(a.v,Za(w(),b));return a}k.t=function(){return Vc(this)};k.Wa=function(a){return hb(this,a)};
k.a=A({Vc:0},!1,"scala.collection.mutable.StringBuilder",{Vc:1,Fe:1,yc:1,vb:1,wb:1,b:1,Fb:1,Gb:1,Jb:1,Hb:1,U:1,T:1,Ab:1,Eb:1,zb:1,Ib:1,Bb:1,xb:1,yb:1,Cb:1,M:1,Hc:1,tb:1,Ja:1,Qa:1,Ac:1,Ic:1,Me:1,Uc:1,Wc:1,rc:1,Ne:1,Oc:1,pc:1,nb:1,lb:1,Ie:1,Bc:1,oe:1,Je:1,Ce:1,pe:1,ie:1,E:1,Nc:1,Kc:1,Jc:1,s:1,e:1});
}).call(this);
//# sourceMappingURL=simplegame-opt.js.map
